[package]
name = "minidump-common"
description = "Some common types for working with minidump files."
version = "0.2.0"
authors = ["Ted Mielczarek <ted@mielczarek.org>"]
readme = "README.md"
license = "MIT"
documentation = "https://docs.rs/minidump-common"
homepage = "https://github.com/luser/rust-minidump"
repository = "https://github.com/luser/rust-minidump"

[badges]
travis-ci = { repository = "luser/rust-minidump" }

[dependencies]
enum-primitive-derive = "0.1"
libc = "0.2.34"
log = "0.4.1"
num-traits = "0.2"
range-map = "0.1.5"
scroll = { version = "0.9.0", features = ["derive"] }
smart-default = "0.5.2"
bitflags = "1.0.4"
