[package]
name = "minidump-common"
description = "Some common types for working with minidump files."
version = "0.9.4"
authors = ["Ted Mielczarek <ted@mielczarek.org>"]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/luser/rust-minidump"
repository = "https://github.com/luser/rust-minidump"
edition = "2018"

[badges]
travis-ci = { repository = "luser/rust-minidump" }

[dependencies]
enum-primitive-derive = "0.2.2"
log = "0.4.1"
num-traits = "0.2"
range-map = "0.1.5"
scroll = { version = "0.10.2", features = ["derive"] }
smart-default = "0.6.0"
bitflags = "1.3.2"
