[package]
name = "minidump-stackwalk"
description = "A CLI minidump analyzer"
version = "0.9.6"
authors = ["Ted Mielczarek <ted@mielczarek.org>"]
license = "MIT"
homepage = "https://github.com/luser/rust-minidump"
repository = "https://github.com/luser/rust-minidump"
keywords = ["breakpad", "symbols"]
categories = ["parsing"]
readme = "README.md"
edition = "2018"

[badges]
travis-ci = { repository = "luser/rust-minidump" }

[dependencies]
clap = { version = "2.33", features=["wrap_help"] }
log = "0.4"
minidump = { version = "0.9.6", path = "../minidump" }
minidump-processor = { version = "0.9.6", path = "../minidump-processor" }
simplelog = "0.11.0"

[features]
vendored-openssl = ["openssl/vendored"]

[dependencies.openssl]
version = "0.10"
optional = true

[dev-dependencies]
insta = "1.3.0"