[package]
name = "minidump-stackwalk"
description = "A CLI minidump analyzer"
version = "0.9.2"
authors = ["Ted Mielczarek <ted@mielczarek.org>"]
license = "MIT"
documentation = "https://docs.rs/minidump-stackwalk"
homepage = "https://github.com/luser/rust-minidump"
repository = "https://github.com/luser/rust-minidump"
keywords = ["breakpad", "symbols"]
categories = ["parsing"]
readme = "README.md"
edition = "2018"

[badges]
travis-ci = { repository = "luser/rust-minidump" }

[dependencies]
addr2line = "0.15.2"
clap = "2.33"
log = "0.4"
minidump = { version = "0.9.2", path = "../minidump" }
minidump-processor = { version = "0.9.2", path = "../minidump-processor" }
simplelog = "0.10.2"

