[package]
name = "minidump-processor"
description = "A library and tool for producing stack traces and other useful information from minidump files."
version = "0.1.0"
authors = ["Ted Mielczarek <ted@mielczarek.org>"]
license = "MIT"
readme = "README.md"
documentation = "https://docs.rs/minidump-processor"
homepage = "https://github.com/luser/rust-minidump"
repository = "https://github.com/luser/rust-minidump"

[badges]
travis-ci = { repository = "luser/rust-minidump" }

[dependencies]
addr2line = "0.7.0"
breakpad-symbols = { version = "0.1.1", path = "../breakpad-symbols" }
chrono = "0.2.16"
failure = "0.1.1"
memmap = "0.6.1"
object = { git = "https://github.com/gimli-rs/object/" }
minidump = { version = "0.1.0", path = ".." }

[dev-dependencies]
test-assembler = "0.1.5"
