[package]
name = "breakpad-symbols"
description = "A library for working with Google Breakpad's text-format symbol files."
version = "0.9.1"
authors = ["Ted Mielczarek <ted@mielczarek.org>"]
license = "MIT"
documentation = "https://docs.rs/breakpad-symbols"
homepage = "https://github.com/luser/rust-minidump"
repository = "https://github.com/luser/rust-minidump"
exclude = [ "testdata/*" ]
edition = "2018"

[badges]
travis-ci = { repository = "luser/rust-minidump" }

[dependencies]
minidump-common = { version = "0.9.1", path = "../minidump-common" }
range-map = "0.1.5"
nom = "~1.2.2"
log = "0.4.1"
reqwest = { version = "0.11.3", features = ["blocking", "gzip"] }
failure = "0.1.1"
tempfile = "3.2.0"

[dev-dependencies]
tempdir = "0.3"
