[package]
name = "breakpad-symbols"
version = "0.1.0"
authors = ["Ted Mielczarek <ted@mielczarek.org>"]
license = "MIT"

[dependencies]
range-map = { path = "../range-map" }
nom = "~0.5.0"
# This is technically test-dependencies, but cargo can't handle that
# when running `cargo test -p breakpad-symbols` from the repository root.
tempdir = "0.3"
