[package]
name = "breakpad-symbols"
description = "A library for working with Google Breakpad's text-format symbol files."
version = "0.9.6"
authors = ["Ted Mielczarek <ted@mielczarek.org>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/luser/rust-minidump"
repository = "https://github.com/luser/rust-minidump"
exclude = [ "testdata/*" ]
edition = "2018"

[badges]
travis-ci = { repository = "luser/rust-minidump" }

[dependencies]
circular = "0.3.0"
minidump-common = { version = "0.9.6", path = "../minidump-common" }
range-map = "0.1.5"
nom = "~1.2.2"
log = "0.4.1"
reqwest = { version = "0.11.6", features = ["blocking", "gzip"] }
tempfile = "3.3.0"
thiserror = "1.0.30"

# Private API, only here to support the fuzzer
[features]
fuzz = []
