[package]
name = "breakpad-symbols"
description = "A library for working with Google Breakpad's text-format symbol files."
version = "0.10.4"
authors = ["Ted Mielczarek <ted@mielczarek.org>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/rust-minidump/rust-minidump"
repository = "https://github.com/rust-minidump/rust-minidump"
exclude = ["testdata/*"]
edition = "2018"

[badges]
travis-ci = { repository = "rust-minidump/rust-minidump" }

[features]
# Private API, only here to support the fuzzer
fuzz = []
# Allow retrieval of symbols via HTTP
http = ["reqwest", "tempfile"]

[dependencies]
async-trait = "0.1.51"
circular = "0.3.0"
debugid = "0.7.3"
log = "0.4.1"
minidump-common = { version = "0.10.4", path = "../minidump-common" }
nom = "~1.2.2"
range-map = "0.1.5"
reqwest = { version = "0.11.6", default-features = false, features = [
    "gzip",
    "rustls-tls",
], optional = true }
tempfile = { version = "3.3.0", optional = true }
thiserror = "1.0.30"

[dev-dependencies]
tempfile = "3.3.0"
tokio = { version = "1.12.0", features = ["full"] }
